### ISSUE TITLE
allow copying trees

### ISSUE THREAD

**Issue by jidanni** [kawanet/XML-TreePP#4]
Currently if one wants a second independent copy,
instead of
           my $tree = $tpp->parse( $xml );
           my $tree2 = $tree; #just a pointer!
one must parse a second time:
           my $tree = $tpp->parse( $xml );
           my $tree2 = $tpp->parse( $xml );

Please add instructions on how to copy tree contents, not just pointers.

**Comment by kawanet** [comment]
Call `parse()` again, or use other modules to perform deep copying: 
- http://search.cpan.org/dist/Clone/Clone.pm `clone($tree)`
- http://search.cpan.org/dist/Storable/Storable.pm `dclone($tree)`
